import { test, expect } from "@playwright/test";
import { LoginPinPage } from "./PageObjects/LoginPin";

test.describe("Create Account and Login Tests", () => {
  test("test 1", async ({ page }) => {
    const loginPinPage = new LoginPinPage(page);
    await page.goto("http://localhost:5173/");
    await page.goto("http://localhost:5173/auth/unlock");
    await loginPinPage.pinButton1.click();
    await loginPinPage.pinButton2.click();
    await loginPinPage.pinButton3.click();
    await loginPinPage.pinButton4.click();
    await page.getByTestId("button-settings").click();
    await page.locator(".slider").last().click();
    await page.getByTestId("button-confirm-pin").click();
    await page.getByPlaceholder("Enter a username . .").click();
    await page.getByPlaceholder("Enter a username . .").fill("test123");
    await page.getByPlaceholder("Set status message . .").click();
    await page.getByPlaceholder("Set status message . .").fill("statys");
    await page.getByRole("button", { name: "Create Account" }).click();
    await page.getByRole("button", { name: "Settings" }).click();
    await page.getByRole("button", { name: "Log Out" }).click();
    await page.getByRole("button", { name: "1" }).click();
    await page.getByRole("button", { name: "2" }).click();
    await page.getByRole("button", { name: "5" }).click();
    await page.getByRole("button", { name: "9" }).click();
    await page.locator("button:nth-child(12)").click();
    await page.getByRole("button", { name: "1" }).click();
    await page.getByRole("button", { name: "2" }).click();
    await page.getByRole("button", { name: "3" }).click();
    await page.getByRole("button", { name: "4" }).click();
    await page.locator("button:nth-child(12)").click();
    await page.goto("http://localhost:5173/");
    await page.goto("http://localhost:5173/auth/unlock");
    await page.getByRole("button", { name: "1" }).click();
    await page.getByRole("button", { name: "2" }).click();
    await page.getByRole("button", { name: "5" }).click();
    await page.getByRole("button", { name: "6" }).click();
    await page.locator("button:nth-child(12)").click();
    await page.getByRole("button", { name: "1" }).click();
    await page.getByRole("button", { name: "2" }).click();
    await page.getByRole("button", { name: "3" }).click();
    await page.getByRole("button", { name: "4" }).click();
    await page.locator("button:nth-child(12)").click();
  });

  test("test 2", async ({ page }) => {
    await page.goto("http://localhost:5173/");
    await page.goto("http://localhost:5173/auth/unlock");
    await page.getByTestId("button-pin-1").click();
    await page.getByTestId("button-pin-2").click();
    await page.getByTestId("button-pin-3").click();
    await page.getByTestId("button-pin-4").click();
    await page.getByTestId("button-settings").click();
    await page.locator(".slider").last().click();
    await page.getByTestId("button-confirm-pin").click();
    await page.getByPlaceholder("Enter a username . .").click();
    await page.getByPlaceholder("Enter a username . .").fill("test123");
    await page.getByPlaceholder("Set status message . .").click();
    await page.getByPlaceholder("Set status message . .").fill("statys");
    await page.getByRole("button", { name: "Create Account" }).click();
    await page.getByRole("button", { name: "Settings" }).click();
    await page.getByRole("button", { name: "Log Out" }).click();
    await page.getByRole("button", { name: "1" }).click();
    await page.getByRole("button", { name: "2" }).click();
    await page.getByRole("button", { name: "5" }).click();
    await page.getByRole("button", { name: "9" }).click();
    await page.locator("button:nth-child(12)").click();
    await page.getByRole("button", { name: "1" }).click();
    await page.getByRole("button", { name: "2" }).click();
    await page.getByRole("button", { name: "3" }).click();
    await page.getByRole("button", { name: "4" }).click();
    await page.locator("button:nth-child(12)").click();
    await page.goto("http://localhost:5173/");
    await page.goto("http://localhost:5173/auth/unlock");
    await page.getByRole("button", { name: "1" }).click();
    await page.getByRole("button", { name: "2" }).click();
    await page.getByRole("button", { name: "5" }).click();
    await page.getByRole("button", { name: "6" }).click();
    await page.locator("button:nth-child(12)").click();
    await page.getByRole("button", { name: "1" }).click();
    await page.getByRole("button", { name: "2" }).click();
    await page.getByRole("button", { name: "3" }).click();
    await page.getByRole("button", { name: "4" }).click();
    await page.locator("button:nth-child(12)").click();
  });
});
