name: Add Label
on:
  pull_request:
    types:
      - opened
jobs:
  add-label:
    name: Add Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: christianvuerings/add-labels@v1
        with:
          labels: |
            Missing dev review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
