name: Automatically fix typos
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
      - uses: sobolevn/misspell-fixer-action@master
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check outputs of PR
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
