name: Playwright Tests

on:
  schedule:
    - cron: "0 0/6 * * 1-5"
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - ".gitignore"
      - ".prettierignore"
      - ".prettierrc.json"
      - "PULL_REQUEST_TEMPLATE.md"
      - "README.md"
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.48.0-jammy
    strategy:
      fail-fast: false
      matrix:
        project: ["desktop-chrome", "mobile-chrome"]
    steps:
      - name: Checkout Uplink Web directory 🔖
        uses: actions/checkout@v4
        with:
          repository: Satellite-im/UplinkWeb
          ref: call-ui-rework

      - name: Checkout Automated Tests directory 🔖
        uses: actions/checkout@v4
        with:
          path: automated-tests

      - name: Setup Node.js for Uplink Web 🔨
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies for Uplink Web 📦
        run: npm install

      - name: Install dependencies for Testing Repo 📦
        working-directory: automated-tests
        run: npm ci

      - name: Install Allure Commandline
        run: npm install -g allure-commandline

      - name: Run Playwright tests
        working-directory: automated-tests
        run: npx playwright test -c playwright.ci.config.ts --project=${{ matrix.project }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.project }}
          path: automated-tests/blob-report/
          retention-days: 1

      - name: Upload Allure results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.project }}
          path: automated-tests/allure-results
          retention-days: 1

      - name: Add label if any of build jobs failed
        if: failure()
        uses: buildsville/add-remove-label@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            Failed Automated Test
          type: add

  merge-reports:
    if: always()
    needs: test
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.48.0-jammy
    steps:
      - name: Download Blob Report from Desktop
        uses: actions/download-artifact@v4
        with:
          name: playwright-report-desktop-chrome
          path: blob-report

      - name: Download Blob Report from Mobile
        uses: actions/download-artifact@v4
        with:
          name: playwright-report-mobile-chrome
          path: blob-report

      - name: Merge Blob Reports into HTML Report
        run: npx playwright merge-reports --reporter html ./blob-report

      - name: Upload Merged Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-merged-report
          path: playwright-report
          retention-days: 5

      - name: Delete temporary artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            playwright-report-desktop-chrome
            playwright-report-mobile-chrome

      - name: Add label if job fails
        if: failure()
        uses: buildsville/add-remove-label@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            Failed Automated Test
          type: add

  publish-report:
    if: always()
    needs: merge-reports
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: write
      issues: read
    steps:
      - name: Download Merged Report
        uses: actions/download-artifact@v4
        with:
          name: playwright-merged-report
          path: playwright-report

      - name: Set a timestamp one
        id: timestampidone
        # this will store current time with UTC in outputs.timestamp (eg of value: 20231028_233147Z)
        run: echo "timestamp=$(date --utc +%Y%m%d_%H%M%SZ)" >> "$GITHUB_OUTPUT"

      - name: Deploy Playwright HTML report to Github Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: Satellite-im/test-reports
          keep_files: true
          publish_branch: gh-pages
          publish_dir: ./playwright-report
          destination_dir: ${{ steps.timestampidone.outputs.timestamp }}

      - name: Stop ssh-agent job from first deploy required for deploying a second time
        run: killall ssh-agent

      - name: Download Allure results artifact for desktop
        uses: actions/download-artifact@v4
        with:
          name: allure-results-desktop-chrome
          path: allure/desktop-chrome

      - name: Download Allure results artifact for mobile
        uses: actions/download-artifact@v4
        with:
          name: allure-results-mobile-chrome
          path: allure/mobile-chrome

      - name: Merge Allure results
        run: |
          mkdir -p allure-results
          cp -r allure/desktop-chrome/* allure-results/
          cp -r allure/mobile-chrome/* allure-results/

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          repository: Satellite-im/test-reports
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          gh_pages: gh-pages
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 100
          github_repo: Satellite-im/test-reports
          github_repo_owner: Satellite-im

      - name: Set a timestamp two
        id: timestampidtwo
        # this will store current time with UTC in outputs.timestamp (eg of value: 20231028_233147Z)
        run: echo "timestamp=$(date --utc +%Y%m%d_%H%M%SZ)" >> "$GITHUB_OUTPUT"

      - name: Deploy report to Github Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: Satellite-im/test-reports
          publish_branch: gh-pages
          publish_dir: ./allure-history

      - name: Comment PR with Test Report link
        if: always() && github.event_name == 'pull_request'
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            Automated tests execution is complete! You can find the Playwright test report [here](https://satellite-im.github.io/test-reports/${{ steps.timestampidone.outputs.timestamp }}/) and the Allure Test Report [here](https://satellite-im.github.io/test-reports/${{ github.run_number }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add label if any of build jobs failed
        if: failure()
        uses: buildsville/add-remove-label@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            Failed Automated Test
          type: add

  remove-label:
    needs: [test, merge-reports, publish-report]
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: write
      issues: read

    steps:
      - name: Checkout directory 🔖
        uses: actions/checkout@v4

      - name: Delete artifacts required on failed execution
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            playwright-merged-report
            allure-results-desktop-chrome
            allure-results-mobile-chrome

      - name: Remove label if all test jobs succeeded
        uses: buildsville/add-remove-label@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            Failed Automated Test
          type: remove
