name: Playwright Tests

on:
  schedule:
    - cron: "0 0/6 * * 1-5"
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - ".gitignore"
      - ".prettierignore"
      - ".prettierrc.json"
      - "PULL_REQUEST_TEMPLATE.md"
      - "README.md"
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.47.2-jammy
    strategy:
      fail-fast: false
      matrix:
        project: ["desktop-chrome", "mobile-chrome"]
    steps:
      - name: Checkout Uplink Web directory 🔖
        uses: actions/checkout@v4
        with:
          repository: Satellite-im/UplinkWeb

      - name: Checkout Automated Tests directory 🔖
        uses: actions/checkout@v4
        with:
          path: automated-tests

      - name: Setup Node.js for Uplink Web 🔨
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies for Uplink Web 📦
        run: npm install

      - name: Install dependencies for Testing Repo 📦
        working-directory: automated-tests
        run: npm ci

      - name: Install Allure Commandline
        run: npm install -g allure-commandline

      - name: Run Playwright tests
        working-directory: automated-tests
        run: npx playwright test -c playwright.ci.config.ts --project=${{ matrix.project }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.project }}
          path: automated-tests/blob-report/
          retention-days: 1

      - name: Upload Allure results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.project }}
          path: automated-tests/allure-results
          retention-days: 1

      - name: Add label if any of build jobs failed
        if: failure()
        uses: buildsville/add-remove-label@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            Failed Automated Test
          type: add

  generate-report:
    if: always()
    needs: test
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.47.2-jammy
    steps:
      - name: Checkout Automated Tests directory 🔖
        uses: actions/checkout@v4
        with:
          path: automated-tests

      - name: Install dependencies for Testing Repo 📦
        working-directory: automated-tests
        run: npm ci

      - name: Download Blob Report from Desktop
        uses: actions/download-artifact@v4
        with:
          name: playwright-report-desktop-chrome
          path: automated-tests/blob-report

      - name: Download Blob Report from Mobile
        uses: actions/download-artifact@v4
        with:
          name: playwright-report-mobile-chrome
          path: automated-tests/blob-report

      - name: Merge Blob Reports into HTML Report
        run: npx playwright merge-reports --reporter html ./blob-report

      - name: Download Allure results artifact for desktop
        uses: actions/download-artifact@v4
        with:
          name: allure-results-desktop-chrome
          path: automated-tests/allure/desktop-chrome

      - name: Download Allure results artifact for mobile
        uses: actions/download-artifact@v4
        with:
          name: allure-results-mobile-chrome
          path: automated-tests/allure/mobile-chrome

      - name: Merge Allure results
        run: |
          mkdir -p automated-tests/allure-results
          cp -r automated-tests/allure/desktop-chrome/* automated-tests/allure-results/
          cp -r automated-tests/allure/mobile-chrome/* automated-tests/allure-results/

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          repository: Satellite-im/test-reports
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          gh_pages: gh-pages
          allure_results: automated-tests/allure-results
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 100

      - name: Deploy Allure report to Github Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: Satellite-im/test-reports
          publish_branch: gh-pages
          publish_dir: allure-history
          allow_empty_commit: true
          destination_dir: allure

      - name: Deploy Playwright HTML report to Github Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: Satellite-im/test-reports
          publish_branch: gh-pages
          publish_dir: automated-tests/playwright-report
          allow_empty_commit: true
          destination_dir: playwright

      - name: Comment PR with Allure test results
        if: always() && github.event_name == 'pull_request'
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            Automated tests execution is complete! You can find the Playwright test report [here](https://satellite-im.github.io/test-reports/playwright/${{ github.run_number }}) and the Allure test report [here](https://satellite-im.github.io/test-reports/allure/${{ github.run_number }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add label if any of build jobs failed
        if: failure()
        uses: buildsville/add-remove-label@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            Failed Automated Test
          type: add

  remove-label:
    needs: [test, generate-report]
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: write
      issues: read

    steps:
      - name: Checkout directory 🔖
        uses: actions/checkout@v4

      - name: Delete artifacts required on failed execution
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            playwright-report-desktop-chrome
            playwright-report-mobile-chrome
            allure-results-desktop-chrome
            allure-results-mobile-chrome

      - name: Remove label if all test jobs succeeded
        uses: buildsville/add-remove-label@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            Failed Automated Test
          type: remove
