name: Playwright Tests

on:
  schedule:
    - cron: "0 0/6 * * 1-5"
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - ".github/workflows/**"
      - "!.github/workflows/automated-tests.yml"
      - "!.github/workflows/playwright.yml"
      - ".gitignore"
      - ".prettierignore"
      - ".prettierrc.json"
      - "PULL_REQUEST_TEMPLATE.md"
      - "README.md"
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Uplink Web directory 🔖
        uses: actions/checkout@v4
        with:
          repository: Satellite-im/UplinkWeb

      - name: Checkout Automated Tests directory 🔖
        uses: actions/checkout@v4
        with:
          path: automated-tests

      - name: Setup Node.js for Uplink Web 🔨
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies for Uplink Web 📦
        run: npm install

      - name: Install dependencies for Testing Repo 📦
        working-directory: automated-tests
        run: npm install

      - name: Install Playwright Browsers
        working-directory: automated-tests
        run: npx playwright install --with-deps

      - name: Install Allure Commandline
        run: npm install -g allure-commandline

      - name: Run server for Uplink Web
        run: npm run dev &

      - name: Run Playwright tests with Allure reporter
        working-directory: automated-tests
        run: npx playwright test --reporter=line,allure-playwright

      - name: Upload Allure results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: automated-tests/allure-results

      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          gh_pages: gh-pages
          allure_results: automated-tests/allure-results
          allure_report: automated-tests/playwright-report
          allure_history: allure-history
          keep_reports: 100

      - name: Deploy Playwright report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: automated-tests/playwright-report

      - name: Deploy report to Github Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: Satellite-im/test-reports
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Comment PR with Allure test results
        if: always() && github.event_name == 'pull_request'
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            Playwright test execution is complete! You can find the test results report [here](https://satellite-im.github.io/test-reports/${{ github.run_number }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
